import { createContext, useContext, useState, useEffect, useMemo } from 'react';
import { Actor, HttpAgent } from '@dfinity/agent';
import { useAuth } from './AuthContext';

// Import the Snit canister interface
// This will be generated by `dfx generate snit`
import { idlFactory } from 'declarations/snit';

const ActorContext = createContext(null);

// Canister ID from environment
const SNIT_CANISTER_ID = process.env.CANISTER_ID_SNIT;

export function ActorProvider({ children }) {
  const { agent, isAuthenticated, isLoading: authLoading } = useAuth();
  const [anonymousAgent, setAnonymousAgent] = useState(null);

  // Create anonymous agent for unauthenticated queries
  useEffect(() => {
    const initAnonymousAgent = async () => {
      const anonAgent = new HttpAgent({
        host: process.env.DFX_NETWORK === 'ic'
          ? 'https://ic0.app'
          : 'http://127.0.0.1:4943'
      });

      // Fetch root key for local development
      if (process.env.DFX_NETWORK !== 'ic') {
        await anonAgent.fetchRootKey();
      }

      setAnonymousAgent(anonAgent);
    };

    initAnonymousAgent();
  }, []);

  // Create authenticated actor (for update calls)
  const authenticatedActor = useMemo(() => {
    if (!agent || !SNIT_CANISTER_ID) return null;

    return Actor.createActor(idlFactory, {
      agent,
      canisterId: SNIT_CANISTER_ID,
    });
  }, [agent]);

  // Create anonymous actor (for query calls when not authenticated)
  const anonymousActor = useMemo(() => {
    if (!anonymousAgent || !SNIT_CANISTER_ID) return null;

    return Actor.createActor(idlFactory, {
      agent: anonymousAgent,
      canisterId: SNIT_CANISTER_ID,
    });
  }, [anonymousAgent]);

  // Main actor - use authenticated if available, otherwise anonymous
  const actor = useMemo(() => {
    return authenticatedActor || anonymousActor;
  }, [authenticatedActor, anonymousActor]);

  const value = {
    actor,                  // Main actor (authenticated if logged in, anonymous otherwise)
    authenticatedActor,     // Always authenticated (null if not logged in)
    anonymousActor,         // Always anonymous
    canisterId: SNIT_CANISTER_ID,
    isReady: !!actor,
    isAuthLoading: authLoading,
  };

  return (
    <ActorContext.Provider value={value}>
      {children}
    </ActorContext.Provider>
  );
}

export function useActor() {
  const context = useContext(ActorContext);
  if (!context) {
    throw new Error('useActor must be used within an ActorProvider');
  }
  return context;
}

export default ActorContext;
